QA/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('forum.urls', namespace='forum')),

]

account/urls.py
from django.urls import path
from . import views

from .views import (

    UserCreateView,
    UserLoginView,
    UserLogoutView,
    Index,
    ProfileUpdateView,
    ProfileListView,
    ProfileDetailsView,
    ProfileRefreshListView,

)


app_name = 'account'

urlpatterns = [

    path('auth/profile/<str:slug>/update/', ProfileUpdateView.as_view(), name = "profile-update"),
    path('auth/profile/<str:slug>/details/', ProfileDetailsView.as_view(), name = "profile-details"),
    path('auth/profile/list/', ProfileListView.as_view(), name = "profile-list"),
    path('auth/register/', UserCreateView.as_view(), name = "register"),
    path('auth/login/', UserLoginView.as_view(), name="signup"),
    path('auth/refresh/', ProfileRefreshListView.as_view(), name = "profile-list"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    path('', Index.as_view(), name="index"),
    # path("landing/", views.landing, name="landing"),
    # path("profile/", views.profile, name="profile"),
    # path("Create_question/", views.createquestion, name="create_question"),
    # path("SocialNetwork/", views.sociale, name="Network"),
]

templates/site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions & Answers </title>

        {% include "site/css.html" %}
</head>
{% include "site/navbar.html" %}
<body>

    <div class="mt-5 pt-5">
        {% if messages %}
            {% for message in messages %}
            <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}

        <div class="row">
            <div class="col-10">
            {% block content %}
            {% endblock content %}
            </div>
            <div class="col-2">
                {% include "site/sidebar.html" %}
            </div>
        </div>
    </div>

</body>
</html>

templates/site/css.html
<link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
<script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }


</style>

templates/site/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'account:index' %}"><strong class="blue-text">Q&A</strong></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse mx-auto navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:index' %}">Account<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:index' %}">API<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:index' %}">Forum<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Utilisateur
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'account:register' %}">S'inscrire</a>
                    <a class="dropdown-item" href="{% url 'account:signup' %}">Se connecter</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:profile-list' %}">Liste des profils</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">Se déconnecter</a>
                </div>
              </li>
            </ul>
          <!-- Collapse -->

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

          <!-- Links -->

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                {% comment %}
                    <li class="nav-item active">
                        <a class="nav-link waves-effect" href="/">Home
                          <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="/checkout">Checkout</a>
                    </li>
                {% endcomment %}
            </ul>
      </div>
    </div>
  </nav>

templates/site/sidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <p>test</p>
</head>
<body>

</body>
</html>